#ifndef LICENSING_AWSBILLINGPRODUCTS_H
#define LICENSING_AWSBILLINGPRODUCTS_H

#include <string>

const std::string AWS_BILLINGPRODUCTS{"@MAPD_AWS_BILLINGPRODUCTS@"};

#endif  // LICENSING_AWSBILLINGPRODUCTS_H
