#ifndef LINETEMPLATE_FRAG_H_
#define LINETEMPLATE_FRAG_H_

#include <string>

namespace QueryRenderer {
struct LineTemplate_Frag {
  static const std::string source;
};

const std::string LineTemplate_Frag::source =
    "#version 450 core\n"
    "\n"
    "layout(location = 0) out vec4 finalColor;\n"
    "layout(location = 1) out uint finalId;\n"
    "layout(location = 2) out int finalTableId;\n"
    "\n"
    "uniform int uTableId;\n"
    "#define usePerVertId <usePerVertId>\n"
    "#define useUid <useUid>\n"
    "#if usePerVertId == 1\n"
    "flat in uint fId;\n"
    "#elif useUid == 1\n"
    "uniform uint id;\n"
    "#endif\n"
    "\n"
    "#define usePerVertColor <usePerVertColor>\n"
    "#define useUstrokeColor <useUstrokeColor>\n"
    "#define inTstrokeColor <inTstrokeColorType>\n"
    "#define inTstrokeColorEnum <inTstrokeColorEnum>\n"
    "#define outTstrokeColor <outTstrokeColorType>\n"
    "#define outTstrokeColorEnum <outTstrokeColorEnum>\n"
    "#if usePerVertColor == 1\n"
    "in vec4 fColor;\n"
    "#elif useUstrokeColor == 1\n"
    "uniform inTstrokeColor strokeColor;\n"
    "#endif\n"
    "\n"
    "#define useUlineJoin <useUlineJoin>\n"
    "#if useUlineJoin == 1\n"
    "uniform int lineJoin;\n"
    "#endif\n"
    "\n"
    "#define useUniformBuffer <useUniformBuffer>\n"
    "#if useUniformBuffer == 1\n"
    "<lineData>\n"
    "#endif\n"
    "\n"
    "#if usePerVertColor == 0\n"
    // TODO(croot): create a set of color utility functions that
    // can be added #include -- need to create the utility functions
    // and create an ability to #include utilities
    "subroutine vec4 TransformColorToRGBSubroutine(in vec4);\n"
    "subroutine uniform TransformColorToRGBSubroutine transformColorToRGB;\n"
    "subroutine(TransformColorToRGBSubroutine) vec4 transformRGBtoRGB(in vec4 incolorRGB) {\n"
    "    return incolorRGB;\n"
    "}\n"
    "\n"
    "subroutine(TransformColorToRGBSubroutine) vec4 transformHSLtoRGB(in vec4 incolorHSL) {\n"
    "    float h = mod(incolorHSL[0], 360.0), s = incolorHSL[1], l = incolorHSL[2];\n"
    "    if (h < 0) {\n"
    "        h += 360.0;\n"
    "    }\n"
    "    float r = 0, g = 0, b = 0;\n"
    "    float C = s * (1 - abs(2 * l - 1));\n"
    "    float X = C * (1 - abs(mod(h / 60.0, 2.0) - 1));\n"
    "    float m = l - C / 2.0;\n"
    "\n"
    "    int huecat = int(h / 60.0);\n"
    "    if (huecat == 0) {\n"
    "        r = C;\n"
    "        g = X;\n"
    "    } else if (huecat == 1) {\n"
    "        r = X;\n"
    "        g = C;\n"
    "    } else if (huecat == 2) {\n"
    "        g = C;\n"
    "        b = X;\n"
    "    } else if (huecat == 3) {\n"
    "        g = X;\n"
    "        b = C;\n"
    "    } else if (huecat == 4) {\n"
    "        r = X;\n"
    "        b = C;\n"
    "    } else {\n"
    "        r = C;\n"
    "        b = X;\n"
    "    }\n"
    "\n"
    "    return vec4(r + m, g + m, b + m, incolorHSL[3]);\n"
    "}\n"
    "\n"
    "const float Kn = 18,\n"
    "              Xn = 0.950470,  // D65 standard referent\n"
    "              Yn = 1, Zn = 1.088830, \n"
    "              t0 = 4.0 / 29.0, t1 = 6.0 / 29.0,\n"
    "              t2 = 3.0 * pow(6.0 / 29.0, 2.0),\n"
    "              t3 = pow(6.0 / 29.0, 3.0);\n"
    "\n"
    "float xyz2rgb(in float xyzchannel) {\n"
    "    return (xyzchannel <= 0.0031308 ? 12.92 * xyzchannel : 1.055 * pow(xyzchannel, 1 / 2.4) - 0.055);\n"
    "}\n"
    "\n"
    "float lab2xyz(in float labchannel) {\n"
    "    return (labchannel > t1 ? labchannel * labchannel * labchannel : t2 * (labchannel - t0));\n"
    "}\n"
    "\n"
    "subroutine(TransformColorToRGBSubroutine) vec4 transformLABtoRGB(in vec4 incolorLAB) {\n"
    "    float y = (incolorLAB[0] + 16.0) / 116.0, x = isnan(incolorLAB[1]) ? y : y + incolorLAB[1] / 500.0,\n"
    "          z = isnan(incolorLAB[2]) ? y : y - incolorLAB[2] / 200.0;\n"
    "    y = Yn * lab2xyz(y);\n"
    "    x = Xn * lab2xyz(x);\n"
    "    z = Zn * lab2xyz(z);\n"
    "    return vec4(xyz2rgb(3.2404542 * x - 1.5371385 * y - 0.4985314 * z),  // D65 -> sRGB\n"
    "                xyz2rgb(-0.9692660 * x + 1.8760108 * y + 0.0415560 * z),\n"
    "                xyz2rgb(0.0556434 * x - 0.2040259 * y + 1.0572252 * z),\n"
    "                incolorLAB.a);\n"
    "}\n"
    "\n"
    "subroutine(TransformColorToRGBSubroutine) vec4 transformHCLtoRGB(in vec4 incolorHCL) {\n"
    "    float h = radians(incolorHCL[0]);\n"
    "    return transformLABtoRGB(vec4(incolorHCL[2], cos(h) * incolorHCL[1], sin(h) * incolorHCL[1], "
    "incolorHCL[3]));\n"
    "}\n"
    "\n"
    "subroutine vec4 UnpackColorSubroutine(in uint);\n"
    "subroutine uniform UnpackColorSubroutine unpackColor;\n"
    "subroutine(UnpackColorSubroutine) vec4 unpackRGBAColor(in uint incolorRGB) {\n"
    "    vec4 color;\n"
    "    color.r = float((incolorRGB >> 24) & 0xFF) / 255.0;\n"
    "    color.g = float((incolorRGB >> 16) & 0xFF) / 255.0;\n"
    "    color.b = float((incolorRGB >> 8) & 0xFF) / 255.0;\n"
    "    color.a = float(incolorRGB & 0xFF) / 255.0;\n"
    "    return color;\n"
    "}\n"
    "\n"
    "subroutine(UnpackColorSubroutine) vec4 unpackLABColor(in uint incolorLAB) {\n"
    "    vec4 color;\n"
    "    color.r = 100.0 * (float((incolorLAB >> 24) & 0xFF) / 255.0);\n"
    "    color.g = 256.0 * (float((incolorLAB >> 16) & 0xFF) / 255.0) - 128.0;\n"
    "    color.b = 256.0 * (float((incolorLAB >> 8) & 0xFF) / 255.0) - 128.0;\n"
    "    color.a = float(incolorLAB & 0xFF) / 255.0;\n"
    "    return color;\n"
    "}\n"
    "\n"
    "outTstrokeColor getstrokeColor(in inTstrokeColor strokeColor) {\n"
    "#if (inTstrokeColorEnum == INT || inTstrokeColorEnum == UNSIGNED_INT) && outTstrokeColorEnum == FLOAT_VEC4\n"
    "    return unpackColor(strokeColor);\n"
    "#else\n"
    "    return strokeColor;\n"
    "#endif\n"
    "}\n"
    "#endif\n"
    "\n"
    "in vec2 fNormDistCoords;\n"
    "flat in int fIsCorner;\n"
    "\n"
    "void main() {\n"
    "  if (fIsCorner == 1) {\n"
    "#if useUlineJoin == 1\n"
    "    if ((lineJoin == 1 && length(fNormDistCoords) > 1) ||\n"
    "        (lineJoin != 1 && fNormDistCoords[0] > 1)) {\n"
    "#else // should be in uniform buffer\n"
    "    if ((lineData.<lineJoin> == 1 && length(fNormDistCoords) > 1) ||\n"
    "        (lineData.<lineJoin> != 1 && fNormDistCoords[0] > 1)) {\n"
    "#endif\n"
    "      discard;\n"
    "    }\n"
    "  }\n"
    "\n"
    "#if usePerVertId == 1\n"
    "  finalId = fId + 1;\n"
    "#elif useUid == 1\n"
    "  finalId = id + 1;\n"
    "#elif useUniformBuffer == 1\n"
    "  finalId = lineData.<id> + 1;\n"
    "#endif\n"
    "\n"
    "#if usePerVertColor == 1\n"
    "  finalColor = fColor;\n"
    "#elif useUstrokeColor == 1\n"
    "  finalColor = transformColorToRGB(getstrokeColor(strokeColor));\n"
    "#elif useUniformBuffer == 1\n"
    "  finalColor = transformColorToRGB(getstrokeColor(lineData.<strokeColor>));\n"
    "#endif\n"
    "  finalTableId = uTableId + 1;\n"
    "\n"
    "}\n";

}  // namespace QueryRenderer

#endif  // LINETEMPLATE_FRAG_H_
